//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP2077SaveEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CP2077SaveEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;EyeColors&quot;:
        ///	[
        ///		&quot;01_blood_gradient_black&quot;,
        ///		&quot;02_blood_gradient_blue&quot;,
        ///		&quot;03_blood_gradient_brown&quot;,
        ///		&quot;04_blood_gradient_green&quot;,
        ///		&quot;05_blood_gradient_grey&quot;,
        ///		&quot;06_blood_gradient_light_blue&quot;,
        ///		&quot;07_blood_gradient_red&quot;,
        ///		&quot;08_blood_gradient_violet&quot;,
        ///		&quot;09_blood_gradient_yellow&quot;,
        ///		&quot;10_gradient_black&quot;,
        ///		&quot;11_gradient_blue&quot;,
        ///		&quot;12_gradient_brown&quot;,
        ///		&quot;13_gradient_green&quot;,
        ///		&quot;14_gradient_grey&quot;,
        ///		&quot;15_gradient_light_blue&quot;,
        ///		&quot;16_gradient_red&quot;,
        ///		&quot;17_gradient_violet&quot;,
        ///		&quot;18_gradient_yellow&quot;, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AppearanceValues {
            get {
                return ResourceManager.GetString("AppearanceValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corpo {
            get {
                object obj = ResourceManager.GetObject("corpo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;2436045487&quot;: &quot;CYB-12345&quot;,
        ///  &quot;2145224326&quot;: &quot;travelling_merchant_lives&quot;,
        ///  &quot;141669211&quot;: &quot;CYB-596812&quot;,
        ///  &quot;2500105824&quot;: &quot;CYB-626716&quot;,
        ///  &quot;2061787877&quot;: &quot;holo_force_reset&quot;,
        ///  &quot;3763092045&quot;: &quot;holo_setup_started&quot;,
        ///  &quot;2143749004&quot;: &quot;holo_setup_ended&quot;,
        ///  &quot;453873154&quot;: &quot;holo_interrupt_call&quot;,
        ///  &quot;1648090866&quot;: &quot;holo_v_calls_panam_end_activate&quot;,
        ///  &quot;1642883195&quot;: &quot;CYB-629334&quot;,
        ///  &quot;2054825040&quot;: &quot;holo_anders_hellman_calls_v_start_done&quot;,
        ///  &quot;2558910171&quot;: &quot;holo_anders_hellman_calls_v_end_done&quot;,
        ///  &quot;1017146762&quot;: &quot;holo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Facts {
            get {
                return ResourceManager.GetString("Facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [{&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_dataterm_01&quot;,&quot;MarkerRef&quot;:&quot;#bls_bls_dataterm_01&quot;},{&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_dataterm_02&quot;,&quot;MarkerRef&quot;:&quot;#bls_bls_dataterm_02&quot;},{&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_dataterm_03&quot;,&quot;MarkerRef&quot;:&quot;#bls_bls_dataterm_new_03&quot;},{&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_dataterm_04&quot;,&quot;MarkerRef&quot;:&quot;#bls_bls_dataterm_04&quot;},{&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_dataterm_05&quot;,&quot;MarkerRef&quot;:&quot;#bls_bls_dataterm_05&quot;},{&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_dataterm_06&quot;,&quot;Ma [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FastTravel {
            get {
                return ResourceManager.GetString("FastTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;DataExists&quot;:1,&quot;Unknown1&quot;:0,&quot;IsBrainGenderMale&quot;:0,&quot;Preset&quot;:{&quot;$type&quot;:&quot;gameuiCharacterCustomizationPreset&quot;,&quot;armsGroups&quot;:[{&quot;$type&quot;:&quot;gameuiCustomizationGroup&quot;,&quot;customization&quot;:[{&quot;$type&quot;:&quot;gameuiCustomizationAppearance&quot;,&quot;censorFlag&quot;:&quot;0&quot;,&quot;censorFlagAction&quot;:&quot;Activate&quot;,&quot;definition&quot;:&quot;holstered_arms_data_female&quot;,&quot;name&quot;:&quot;holstered_data&quot;,&quot;resource&quot;:{&quot;DepotPath&quot;:13328453398705956150,&quot;Flags&quot;:&quot;Soft&quot;}},{&quot;$type&quot;:&quot;gameuiCustomizationAppearance&quot;,&quot;censorFlag&quot;:&quot;0&quot;,&quot;censorFlagAction&quot;:&quot;Activate&quot;,&quot;definition&quot;:&quot;a0_000_pwa_base__nail [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FemaleDefaultPreset {
            get {
                return ResourceManager.GetString("FemaleDefaultPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;37647373161&quot;: {
        ///    &quot;Type&quot;: &quot;Gadget&quot;,
        ///    &quot;IsSingleInstance&quot;: true
        ///  },
        ///  &quot;40557222671&quot;: {
        ///    &quot;Type&quot;: &quot;Clothing&quot;,
        ///    &quot;IsSingleInstance&quot;: false
        ///  },
        ///  &quot;40707698935&quot;: {
        ///    &quot;Type&quot;: &quot;Clothing&quot;,
        ///    &quot;IsSingleInstance&quot;: false
        ///  },
        ///  &quot;42366033259&quot;: {
        ///    &quot;Type&quot;: &quot;Item&quot;,
        ///    &quot;IsSingleInstance&quot;: true
        ///  },
        ///  &quot;42943500278&quot;: {
        ///    &quot;Type&quot;: &quot;Item&quot;,
        ///    &quot;IsSingleInstance&quot;: false
        ///  },
        ///  &quot;43667576622&quot;: {
        ///    &quot;Type&quot;: &quot;Item&quot;,
        ///    &quot;IsSingleInstance&quot;: true
        ///  },
        ///  &quot;44117334148&quot;: {
        ///    &quot;Type&quot;: &quot;G [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ItemClasses {
            get {
                return ResourceManager.GetString("ItemClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;DataExists&quot;:1,&quot;Unknown1&quot;:0,&quot;IsBrainGenderMale&quot;:1,&quot;Preset&quot;:{&quot;$type&quot;:&quot;gameuiCharacterCustomizationPreset&quot;,&quot;armsGroups&quot;:[{&quot;$type&quot;:&quot;gameuiCustomizationGroup&quot;,&quot;customization&quot;:[{&quot;$type&quot;:&quot;gameuiCustomizationAppearance&quot;,&quot;censorFlag&quot;:&quot;0&quot;,&quot;censorFlagAction&quot;:&quot;Activate&quot;,&quot;definition&quot;:&quot;holstered_arms_data_male&quot;,&quot;name&quot;:&quot;holstered_data&quot;,&quot;resource&quot;:{&quot;DepotPath&quot;:13328453398705956150,&quot;Flags&quot;:&quot;Soft&quot;}},{&quot;$type&quot;:&quot;gameuiCustomizationAppearance&quot;,&quot;censorFlag&quot;:&quot;0&quot;,&quot;censorFlagAction&quot;:&quot;Activate&quot;,&quot;definition&quot;:&quot;a0_000_pma_base__nails_ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MaleDefaultPreset {
            get {
                return ResourceManager.GetString("MaleDefaultPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;Clothing&quot;: {
        ///    &quot;152193456621&quot;: [
        ///      122917906251,
        ///      136186757750,
        ///      131341932850,
        ///      132666432922,
        ///      133985117844,
        ///      134256022043,
        ///      130693152003,
        ///      134676177754,
        ///      134304077314,
        ///      138324646011,
        ///      136404677344,
        ///      141046985623,
        ///      133887710156,
        ///      132191677451,
        ///      122530387466,
        ///      118999678073,
        ///      124176390109,
        ///      136837908408,
        ///      125411252595,
        ///      145924706992,
        ///      109070607824,
        ///      134428744233,
        ///      1 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Mods {
            get {
                return ResourceManager.GetString("Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nomad {
            get {
                object obj = ResourceManager.GetObject("nomad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_stats {
            get {
                object obj = ResourceManager.GetObject("player_stats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap streetkid {
            get {
                object obj = ResourceManager.GetObject("streetkid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  &quot;Vehicle.v_sport1_herrera_outlaw_player&quot;,
        ///  &quot;Vehicle.v_sport1_quadra_turbo_player&quot;,
        ///  &quot;Vehicle.v_sport1_quadra_turbo_r_player&quot;,
        ///  &quot;Vehicle.v_sport1_rayfield_aerondight_player&quot;,
        ///  &quot;Vehicle.v_sport1_rayfield_caliburn_02_player&quot;,
        ///  &quot;Vehicle.v_sport1_rayfield_caliburn_player&quot;,
        ///  &quot;Vehicle.v_sport2_mizutani_shion_nomad_02_player&quot;,
        ///  &quot;Vehicle.v_sport2_mizutani_shion_nomad_player&quot;,
        ///  &quot;Vehicle.v_sport2_mizutani_shion_player&quot;,
        ///  &quot;Vehicle.v_sport2_porsche_911turbo_player&quot;,
        ///  &quot;Vehicle.v_sport2_quadra_typ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
    }
}
