//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP2077SaveEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CP2077SaveEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;EyeColors&quot;:
        ///	[
        ///		&quot;01_blood_gradient_black&quot;,
        ///		&quot;02_blood_gradient_blue&quot;,
        ///		&quot;03_blood_gradient_brown&quot;,
        ///		&quot;04_blood_gradient_green&quot;,
        ///		&quot;05_blood_gradient_grey&quot;,
        ///		&quot;06_blood_gradient_light_blue&quot;,
        ///		&quot;07_blood_gradient_red&quot;,
        ///		&quot;08_blood_gradient_violet&quot;,
        ///		&quot;09_blood_gradient_yellow&quot;,
        ///		&quot;10_gradient_black&quot;,
        ///		&quot;11_gradient_blue&quot;,
        ///		&quot;12_gradient_brown&quot;,
        ///		&quot;13_gradient_green&quot;,
        ///		&quot;14_gradient_grey&quot;,
        ///		&quot;15_gradient_light_blue&quot;,
        ///		&quot;16_gradient_red&quot;,
        ///		&quot;17_gradient_violet&quot;,
        ///		&quot;18_gradient_yellow&quot;, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AppearanceValues {
            get {
                return ResourceManager.GetString("AppearanceValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corpo {
            get {
                object obj = ResourceManager.GetObject("corpo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;321819&quot;: &quot;sq024_claire_pose_low&quot;,
        ///  &quot;367985&quot;: &quot;sts_ep1_13_dolls_chat_end&quot;,
        ///  &quot;381979&quot;: &quot;web_smugglers_cache_treasures&quot;,
        ///  &quot;452843&quot;: &quot;q001_takedown_scene_finished&quot;,
        ///  &quot;457750&quot;: &quot;CYB-644974&quot;,
        ///  &quot;490938&quot;: &quot;ma_wat_nid_22_psycho_killed&quot;,
        ///  &quot;591985&quot;: &quot;mq017_kirk_briefing_ended&quot;,
        ///  &quot;1060532&quot;: &quot;q302_caliente_ronald_lookat_loop&quot;,
        ///  &quot;1061235&quot;: &quot;q114_training_hit&quot;,
        ///  &quot;1283730&quot;: &quot;q302_msg_ronald_sts_ep1_12&quot;,
        ///  &quot;1340607&quot;: &quot;q302_corruption_started&quot;,
        ///  &quot;1404642&quot;: &quot;sq021_done_drawer3&quot;,
        ///  &quot;1759124&quot;: &quot;cs_pa [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Facts {
            get {
                return ResourceManager.GetString("Facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [{&quot;IsEP1&quot;:false,&quot;MarkerRef&quot;:&quot;#bls_bls_dataterm_01&quot;,&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_dataterm_01&quot;},{&quot;IsEP1&quot;:false,&quot;MarkerRef&quot;:&quot;#bls_bls_dataterm_02&quot;,&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_dataterm_02&quot;},{&quot;IsEP1&quot;:false,&quot;MarkerRef&quot;:&quot;#bls_bls_dataterm_new_03&quot;,&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_dataterm_03&quot;},{&quot;IsEP1&quot;:false,&quot;MarkerRef&quot;:&quot;#bls_bls_dataterm_04&quot;,&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_dataterm_04&quot;},{&quot;IsEP1&quot;:false,&quot;MarkerRef&quot;:&quot;#bls_bls_dataterm_05&quot;,&quot;PointRecord&quot;:&quot;FastTravelPoints.bls_nth_d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FastTravel {
            get {
                return ResourceManager.GetString("FastTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;DataExists&quot;:1,&quot;Unknown1&quot;:0,&quot;IsBrainGenderMale&quot;:0,&quot;Preset&quot;:{&quot;$type&quot;:&quot;gameuiCharacterCustomizationPreset&quot;,&quot;armsGroups&quot;:[{&quot;$type&quot;:&quot;gameuiCustomizationGroup&quot;,&quot;customization&quot;:[{&quot;$type&quot;:&quot;gameuiCustomizationAppearance&quot;,&quot;censorFlag&quot;:&quot;0&quot;,&quot;censorFlagAction&quot;:&quot;Activate&quot;,&quot;definition&quot;:&quot;holstered_arms_data_female&quot;,&quot;name&quot;:&quot;holstered_data&quot;,&quot;resource&quot;:{&quot;DepotPath&quot;:13328453398705956150,&quot;Flags&quot;:&quot;Soft&quot;}},{&quot;$type&quot;:&quot;gameuiCustomizationAppearance&quot;,&quot;censorFlag&quot;:&quot;0&quot;,&quot;censorFlagAction&quot;:&quot;Activate&quot;,&quot;definition&quot;:&quot;a0_000_pwa_base__nail [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FemaleDefaultPreset {
            get {
                return ResourceManager.GetString("FemaleDefaultPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;37647373161&quot;: {
        ///    &quot;Type&quot;: &quot;Gadget&quot;,
        ///    &quot;IsSingleInstance&quot;: true,
        ///    &quot;IsItemPlus&quot;: 0,
        ///    &quot;SlotParts&quot;: []
        ///  },
        ///  &quot;40557222671&quot;: {
        ///    &quot;Type&quot;: &quot;Clothing&quot;,
        ///    &quot;IsSingleInstance&quot;: false,
        ///    &quot;IsItemPlus&quot;: 0,
        ///    &quot;SlotParts&quot;: []
        ///  },
        ///  &quot;40707698935&quot;: {
        ///    &quot;Type&quot;: &quot;Clothing&quot;,
        ///    &quot;IsSingleInstance&quot;: false,
        ///    &quot;IsItemPlus&quot;: 0,
        ///    &quot;SlotParts&quot;: []
        ///  },
        ///  &quot;42366033259&quot;: {
        ///    &quot;Type&quot;: &quot;Item&quot;,
        ///    &quot;IsSingleInstance&quot;: true,
        ///    &quot;IsItemPlus&quot;: 0,
        ///    &quot;SlotParts&quot;: []
        ///  },
        ///  &quot;4294350027 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ItemClasses {
            get {
                return ResourceManager.GetString("ItemClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;DataExists&quot;:1,&quot;Unknown1&quot;:0,&quot;IsBrainGenderMale&quot;:1,&quot;Preset&quot;:{&quot;$type&quot;:&quot;gameuiCharacterCustomizationPreset&quot;,&quot;armsGroups&quot;:[{&quot;$type&quot;:&quot;gameuiCustomizationGroup&quot;,&quot;customization&quot;:[{&quot;$type&quot;:&quot;gameuiCustomizationAppearance&quot;,&quot;censorFlag&quot;:&quot;0&quot;,&quot;censorFlagAction&quot;:&quot;Activate&quot;,&quot;definition&quot;:&quot;holstered_arms_data_male&quot;,&quot;name&quot;:&quot;holstered_data&quot;,&quot;resource&quot;:{&quot;DepotPath&quot;:13328453398705956150,&quot;Flags&quot;:&quot;Soft&quot;}},{&quot;$type&quot;:&quot;gameuiCustomizationAppearance&quot;,&quot;censorFlag&quot;:&quot;0&quot;,&quot;censorFlagAction&quot;:&quot;Activate&quot;,&quot;definition&quot;:&quot;a0_000_pma_base__nails_ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MaleDefaultPreset {
            get {
                return ResourceManager.GetString("MaleDefaultPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;40732117&quot;: &quot;ModifierGroups.IntelligenceCyberwareSpecialized&quot;,
        ///  &quot;57002797&quot;: &quot;ModifierGroups.ReflexesCyberwareAdvancedDriverUpdate&quot;,
        ///  &quot;218059473&quot;: &quot;ModifierGroups.TechnicalAbilityCyberwareAdvanced&quot;,
        ///  &quot;918553329&quot;: &quot;ModifierGroups.CoolCyberwareAdvancedDriverUpdate&quot;,
        ///  &quot;1084646515&quot;: &quot;ModifierGroups.ReflexesCyberwareSimple&quot;,
        ///  &quot;1184438707&quot;: &quot;ModifierGroups.SimpleCyberwareModifiers&quot;,
        ///  &quot;1186551102&quot;: &quot;ModifierGroups.IntelligenceCyberwareSimple&quot;,
        ///  &quot;1222084776&quot;: &quot;ModifierGroups.BodyCyberwareSimple&quot;,        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ModifierGroups {
            get {
                return ResourceManager.GetString("ModifierGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;Clothing&quot;: {
        ///    &quot;178600545795&quot;: [
        ///      163246605411,
        ///      133869180885,
        ///      133887710156,
        ///      133985117844,
        ///      138324646011,
        ///      134143601343,
        ///      134256022043,
        ///      134304077314,
        ///      134428744233,
        ///      134676177754,
        ///      134691596099,
        ///      136034267959,
        ///      136133527151,
        ///      118999678073,
        ///      136186757750,
        ///      136404677344,
        ///      136452765433,
        ///      136822457249,
        ///      136837908408,
        ///      145924706992
        ///    ],
        ///    &quot;176301629369&quot;: [
        ///      163246605411, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Mods {
            get {
                return ResourceManager.GetString("Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nomad {
            get {
                object obj = ResourceManager.GetObject("nomad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_stats {
            get {
                object obj = ResourceManager.GetObject("player_stats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap streetkid {
            get {
                object obj = ResourceManager.GetObject("streetkid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  &quot;Vehicle.v_sport1_herrera_outlaw_heist_player&quot;,
        ///  &quot;Vehicle.v_sport1_herrera_outlaw_heist_player&quot;,
        ///  &quot;Vehicle.v_sport1_herrera_outlaw_player&quot;,
        ///  &quot;Vehicle.v_sport1_herrera_riptide_player&quot;,
        ///  &quot;Vehicle.v_sport1_quadra_sport_r7_mrhands&quot;,
        ///  &quot;Vehicle.v_sport1_quadra_sport_r7_netrunner&quot;,
        ///  &quot;Vehicle.v_sport1_quadra_sport_r7_player&quot;,
        ///  &quot;Vehicle.v_sport1_quadra_sport_r7_player_02&quot;,
        ///  &quot;Vehicle.v_sport1_quadra_sport_r7_player_02&quot;,
        ///  &quot;Vehicle.v_sport1_quadra_turbo_player&quot;,
        ///  &quot;Vehicle.v_sport1_quadra_turbo_ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
    }
}
